name = "backend"
compatibility_date = "2023-12-01"

# [vars]
# MY_VAR = "my-variable"


[[r2_buckets]]
binding = "DRIVE_BUCKET"
bucket_name = "drive"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

[[unsafe.bindings]]
name = "RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 500, period = 60 }
